// <auto-generated />
using System;
using CloudDentalOffice.Portal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudDentalOffice.Portal.Migrations
{
    [DbContext(typeof(CloudDentalDbContext))]
    [Migration("20260213095809_AddProceduresAndClinicalNotes")]
    partial class AddProceduresAndClinicalNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonForVisit")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentDateTime");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AppointmentDateTime", "ProviderId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdiControlNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientInsuranceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PatientResponsibility")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ServiceDateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServiceDateTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.Property<decimal>("TotalChargeAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ClaimId");

                    b.HasIndex("ClaimNumber")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientInsuranceId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedDate");

                    b.HasIndex("TenantId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.ClaimProcedure", b =>
                {
                    b.Property<int>("ClaimProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AllowedAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CDTCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChargeAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Coinsurance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Copay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Deductible")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.Property<string>("ToothNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimProcedureId");

                    b.HasIndex("CDTCode");

                    b.HasIndex("ClaimId");

                    b.HasIndex("TenantId");

                    b.ToTable("ClaimProcedures");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.ClinicalNote", b =>
                {
                    b.Property<int>("ClinicalNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.HasKey("ClinicalNoteId");

                    b.HasIndex("NoteDate");

                    b.HasIndex("NoteType");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TenantId");

                    b.ToTable("ClinicalNotes");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.InsurancePlan", b =>
                {
                    b.Property<int>("InsurancePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiAuthType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EdiEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EdiPayerId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EdiSubmissionType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpHost")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpPasswordEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SftpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SftpRemotePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpSshKeyEncrypted")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SftpUseSshKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SftpUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("InsurancePlanId");

                    b.HasIndex("PayerId");

                    b.HasIndex("PayerName");

                    b.HasIndex("TenantId");

                    b.ToTable("InsurancePlans");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("Email");

                    b.HasIndex("LastName");

                    b.HasIndex("TenantId");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.PatientInsurance", b =>
                {
                    b.Property<int>("PatientInsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InsurancePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationshipToSubscriber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubscriberDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriberFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriberLastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriberSSN")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientInsuranceId");

                    b.HasIndex("InsurancePlanId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TenantId");

                    b.ToTable("PatientInsurances");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.PlannedProcedure", b =>
                {
                    b.Property<int>("PlannedProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CDTCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClaimProcedureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.Property<string>("ToothNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("TreatmentPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlannedProcedureId");

                    b.HasIndex("ClaimProcedureId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("PlannedProcedures");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Procedure", b =>
                {
                    b.Property<int>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CDTCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChargeAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InsuranceEstimate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PatientPortion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.Property<string>("ToothNumber")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcedureId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("CDTCode");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ServiceDate");

                    b.HasIndex("TenantId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.ProcedureCode", b =>
                {
                    b.Property<int>("ProcedureCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbbrDesc")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProcedureCodeId");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("ProcedureCodes");

                    b.HasData(
                        new
                        {
                            ProcedureCodeId = 1,
                            AbbrDesc = "Periodic Exam",
                            Category = "Diagnostic",
                            Code = "D0120",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9330),
                            DefaultFee = 75.00m,
                            Description = "Periodic oral evaluation - established patient",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 2,
                            AbbrDesc = "Limited Exam",
                            Category = "Diagnostic",
                            Code = "D0140",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9330),
                            DefaultFee = 65.00m,
                            Description = "Limited oral evaluation - problem focused",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 3,
                            AbbrDesc = "Comp Exam",
                            Category = "Diagnostic",
                            Code = "D0150",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9340),
                            DefaultFee = 95.00m,
                            Description = "Comprehensive oral evaluation - new or established patient",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 4,
                            AbbrDesc = "FMX",
                            Category = "Diagnostic",
                            Code = "D0210",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9340),
                            DefaultFee = 125.00m,
                            Description = "Intraoral - complete series of radiographic images",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 5,
                            AbbrDesc = "PA",
                            Category = "Diagnostic",
                            Code = "D0220",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9340),
                            DefaultFee = 35.00m,
                            Description = "Intraoral - periapical first radiographic image",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 6,
                            AbbrDesc = "PA Add'l",
                            Category = "Diagnostic",
                            Code = "D0230",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9340),
                            DefaultFee = 25.00m,
                            Description = "Intraoral - periapical each additional radiographic image",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 7,
                            AbbrDesc = "BW Single",
                            Category = "Diagnostic",
                            Code = "D0270",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9340),
                            DefaultFee = 30.00m,
                            Description = "Bitewing - single radiographic image",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 8,
                            AbbrDesc = "4 BWs",
                            Category = "Diagnostic",
                            Code = "D0274",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9340),
                            DefaultFee = 65.00m,
                            Description = "Bitewings - four radiographic images",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 9,
                            AbbrDesc = "Pano",
                            Category = "Diagnostic",
                            Code = "D0330",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9350),
                            DefaultFee = 95.00m,
                            Description = "Panoramic radiographic image",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 10,
                            AbbrDesc = "Adult Prophy",
                            Category = "Preventive",
                            Code = "D1110",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9350),
                            DefaultFee = 95.00m,
                            Description = "Prophylaxis - adult",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 11,
                            AbbrDesc = "Child Prophy",
                            Category = "Preventive",
                            Code = "D1120",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9350),
                            DefaultFee = 75.00m,
                            Description = "Prophylaxis - child",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 12,
                            AbbrDesc = "Fluoride Varnish",
                            Category = "Preventive",
                            Code = "D1206",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9350),
                            DefaultFee = 35.00m,
                            Description = "Topical application of fluoride varnish",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 13,
                            AbbrDesc = "Fluoride Treatment",
                            Category = "Preventive",
                            Code = "D1208",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9350),
                            DefaultFee = 30.00m,
                            Description = "Topical application of fluoride - excluding varnish",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 14,
                            AbbrDesc = "Sealant",
                            Category = "Preventive",
                            Code = "D1351",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9350),
                            DefaultFee = 55.00m,
                            Description = "Sealant - per tooth",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 15,
                            AbbrDesc = "Amalgam 1 Surf",
                            Category = "Restorative",
                            Code = "D2140",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9360),
                            DefaultFee = 140.00m,
                            Description = "Amalgam - one surface, primary or permanent",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 16,
                            AbbrDesc = "Amalgam 2 Surf",
                            Category = "Restorative",
                            Code = "D2150",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9360),
                            DefaultFee = 175.00m,
                            Description = "Amalgam - two surfaces, primary or permanent",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 17,
                            AbbrDesc = "Amalgam 3 Surf",
                            Category = "Restorative",
                            Code = "D2160",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9360),
                            DefaultFee = 210.00m,
                            Description = "Amalgam - three surfaces, primary or permanent",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 18,
                            AbbrDesc = "Comp 1 Surf Ant",
                            Category = "Restorative",
                            Code = "D2330",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9360),
                            DefaultFee = 155.00m,
                            Description = "Resin-based composite - one surface, anterior",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 19,
                            AbbrDesc = "Comp 2 Surf Ant",
                            Category = "Restorative",
                            Code = "D2331",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9360),
                            DefaultFee = 185.00m,
                            Description = "Resin-based composite - two surfaces, anterior",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 20,
                            AbbrDesc = "Comp 3 Surf Ant",
                            Category = "Restorative",
                            Code = "D2332",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9360),
                            DefaultFee = 220.00m,
                            Description = "Resin-based composite - three surfaces, anterior",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 21,
                            AbbrDesc = "Comp 1 Surf Post",
                            Category = "Restorative",
                            Code = "D2391",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9370),
                            DefaultFee = 165.00m,
                            Description = "Resin-based composite - one surface, posterior",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 22,
                            AbbrDesc = "Comp 2 Surf Post",
                            Category = "Restorative",
                            Code = "D2392",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9370),
                            DefaultFee = 195.00m,
                            Description = "Resin-based composite - two surfaces, posterior",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 23,
                            AbbrDesc = "Comp 3 Surf Post",
                            Category = "Restorative",
                            Code = "D2393",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9370),
                            DefaultFee = 235.00m,
                            Description = "Resin-based composite - three surfaces, posterior",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 24,
                            AbbrDesc = "RCT Anterior",
                            Category = "Endodontics",
                            Code = "D3310",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9370),
                            DefaultFee = 750.00m,
                            Description = "Endodontic therapy, anterior tooth",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 25,
                            AbbrDesc = "RCT Premolar",
                            Category = "Endodontics",
                            Code = "D3320",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9370),
                            DefaultFee = 900.00m,
                            Description = "Endodontic therapy, premolar tooth",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 26,
                            AbbrDesc = "RCT Molar",
                            Category = "Endodontics",
                            Code = "D3330",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9370),
                            DefaultFee = 1150.00m,
                            Description = "Endodontic therapy, molar tooth",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 27,
                            AbbrDesc = "SRP per Quad",
                            Category = "Periodontics",
                            Code = "D4341",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9380),
                            DefaultFee = 240.00m,
                            Description = "Periodontal scaling and root planing - four or more teeth per quadrant",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 28,
                            AbbrDesc = "SRP 1-3 Teeth",
                            Category = "Periodontics",
                            Code = "D4342",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9380),
                            DefaultFee = 140.00m,
                            Description = "Periodontal scaling and root planing - one to three teeth per quadrant",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 29,
                            AbbrDesc = "Upper Denture",
                            Category = "Prosthodontics",
                            Code = "D5110",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9380),
                            DefaultFee = 1500.00m,
                            Description = "Complete denture - maxillary",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 30,
                            AbbrDesc = "Lower Denture",
                            Category = "Prosthodontics",
                            Code = "D5120",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9390),
                            DefaultFee = 1500.00m,
                            Description = "Complete denture - mandibular",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 31,
                            AbbrDesc = "Upper Partial",
                            Category = "Prosthodontics",
                            Code = "D5213",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9390),
                            DefaultFee = 1200.00m,
                            Description = "Partial denture - maxillary, resin base",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 32,
                            AbbrDesc = "Lower Partial",
                            Category = "Prosthodontics",
                            Code = "D5214",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9390),
                            DefaultFee = 1200.00m,
                            Description = "Partial denture - mandibular, resin base",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 33,
                            AbbrDesc = "PFM Pontic",
                            Category = "Prosthodontics",
                            Code = "D6240",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9390),
                            DefaultFee = 950.00m,
                            Description = "Pontic - porcelain fused to high noble metal",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 34,
                            AbbrDesc = "PFM Crown",
                            Category = "Prosthodontics",
                            Code = "D6750",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9390),
                            DefaultFee = 1100.00m,
                            Description = "Crown - porcelain fused to high noble metal",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 35,
                            AbbrDesc = "Implant Placement",
                            Category = "Prosthodontics",
                            Code = "D6010",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9390),
                            DefaultFee = 2000.00m,
                            Description = "Surgical placement of endosteal implant",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 36,
                            AbbrDesc = "Simple Extraction",
                            Category = "Oral Surgery",
                            Code = "D7140",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9400),
                            DefaultFee = 150.00m,
                            Description = "Extraction, erupted tooth or exposed root",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 37,
                            AbbrDesc = "Surgical Extraction",
                            Category = "Oral Surgery",
                            Code = "D7210",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9400),
                            DefaultFee = 250.00m,
                            Description = "Extraction, erupted tooth requiring removal of bone and/or sectioning of tooth",
                            IsActive = true
                        },
                        new
                        {
                            ProcedureCodeId = 38,
                            AbbrDesc = "Impacted Tooth",
                            Category = "Oral Surgery",
                            Code = "D7240",
                            CreatedDate = new DateTime(2026, 2, 13, 9, 58, 9, 610, DateTimeKind.Utc).AddTicks(9400),
                            DefaultFee = 400.00m,
                            Description = "Removal of impacted tooth - completely bony",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseState")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NPI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.HasKey("ProviderId");

                    b.HasIndex("NPI")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.TenantRegistry", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.TreatmentPlan", b =>
                {
                    b.Property<int>("TreatmentPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PresentedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dev");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("TreatmentPlanId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Appointment", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Provider", "Provider")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Claim", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany("Claims")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.PatientInsurance", "PatientInsurance")
                        .WithMany()
                        .HasForeignKey("PatientInsuranceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CloudDentalOffice.Portal.Models.Provider", "Provider")
                        .WithMany("Claims")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PatientInsurance");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.ClaimProcedure", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Claim", "Claim")
                        .WithMany("Procedures")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.ClinicalNote", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.PatientInsurance", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.InsurancePlan", "InsurancePlan")
                        .WithMany("PatientInsurances")
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany("Insurances")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePlan");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.PlannedProcedure", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.ClaimProcedure", "ClaimProcedure")
                        .WithMany()
                        .HasForeignKey("ClaimProcedureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CloudDentalOffice.Portal.Models.TreatmentPlan", "TreatmentPlan")
                        .WithMany("PlannedProcedures")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaimProcedure");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Procedure", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.TreatmentPlan", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Provider", "Provider")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Claim", b =>
                {
                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.InsurancePlan", b =>
                {
                    b.Navigation("PatientInsurances");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Claims");

                    b.Navigation("Insurances");

                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Provider", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Claims");

                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.TreatmentPlan", b =>
                {
                    b.Navigation("PlannedProcedures");
                });
#pragma warning restore 612, 618
        }
    }
}
