// <auto-generated />
using System;
using CloudDentalOffice.Portal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudDentalOffice.Portal.Migrations
{
    [DbContext(typeof(CloudDentalDbContext))]
    [Migration("20260211051125_AddEdiConfigToInsurancePlan")]
    partial class AddEdiConfigToInsurancePlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonForVisit")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentDateTime");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("AppointmentDateTime", "ProviderId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdiControlNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientInsuranceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PatientResponsibility")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ServiceDateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServiceDateTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalChargeAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ClaimId");

                    b.HasIndex("ClaimNumber")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientInsuranceId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedDate");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.ClaimProcedure", b =>
                {
                    b.Property<int>("ClaimProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AllowedAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CDTCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChargeAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Coinsurance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Copay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Deductible")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToothNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimProcedureId");

                    b.HasIndex("CDTCode");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimProcedures");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.InsurancePlan", b =>
                {
                    b.Property<int>("InsurancePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiAuthType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EdiEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EdiPayerId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EdiSubmissionType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpHost")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpPasswordEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SftpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SftpRemotePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SftpSshKeyEncrypted")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SftpUseSshKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SftpUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("InsurancePlanId");

                    b.HasIndex("PayerId");

                    b.HasIndex("PayerName");

                    b.ToTable("InsurancePlans");

                    b.HasData(
                        new
                        {
                            InsurancePlanId = 1,
                            Address1 = "123 Insurance Way",
                            City = "San Francisco",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EdiEnabled = false,
                            EdiPayerId = "BCBS001",
                            IsActive = true,
                            PayerId = "BCBS",
                            PayerName = "Blue Cross Blue Shield",
                            Phone = "1-800-123-4567",
                            PlanName = "PPO Standard",
                            PlanType = "PPO",
                            SftpUseSshKey = false,
                            State = "CA",
                            ZipCode = "94102"
                        },
                        new
                        {
                            InsurancePlanId = 2,
                            Address1 = "456 Dental Plaza",
                            City = "Los Angeles",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EdiEnabled = false,
                            EdiPayerId = "DELTA001",
                            IsActive = true,
                            PayerId = "DELTA",
                            PayerName = "Delta Dental",
                            Phone = "1-800-765-4321",
                            PlanName = "Delta Premier",
                            PlanType = "PPO",
                            SftpUseSshKey = false,
                            State = "CA",
                            ZipCode = "90001"
                        });
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("Email");

                    b.HasIndex("LastName");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.PatientInsurance", b =>
                {
                    b.Property<int>("PatientInsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InsurancePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationshipToSubscriber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubscriberDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriberFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriberLastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriberSSN")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientInsuranceId");

                    b.HasIndex("InsurancePlanId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientInsurances");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.PlannedProcedure", b =>
                {
                    b.Property<int>("PlannedProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CDTCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClaimProcedureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToothNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("TreatmentPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlannedProcedureId");

                    b.HasIndex("ClaimProcedureId");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("PlannedProcedures");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseState")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NPI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ProviderId");

                    b.HasIndex("NPI")
                        .IsUnique();

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            ProviderId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dr.johnson@clouddental.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            LicenseNumber = "DDS-12345",
                            LicenseState = "CA",
                            NPI = "1234567890",
                            Phone = "555-123-4567",
                            Specialty = "General Dentistry",
                            Suffix = "DDS",
                            TaxId = "12-3456789"
                        },
                        new
                        {
                            ProviderId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dr.chen@clouddental.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Chen",
                            LicenseNumber = "DMD-54321",
                            LicenseState = "CA",
                            NPI = "0987654321",
                            Phone = "555-987-6543",
                            Specialty = "Orthodontics",
                            Suffix = "DMD",
                            TaxId = "98-7654321"
                        });
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.TreatmentPlan", b =>
                {
                    b.Property<int>("TreatmentPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PresentedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("TreatmentPlanId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Appointment", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Provider", "Provider")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Claim", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany("Claims")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.PatientInsurance", "PatientInsurance")
                        .WithMany()
                        .HasForeignKey("PatientInsuranceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Provider", "Provider")
                        .WithMany("Claims")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PatientInsurance");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.ClaimProcedure", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Claim", "Claim")
                        .WithMany("Procedures")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.PatientInsurance", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.InsurancePlan", "InsurancePlan")
                        .WithMany("PatientInsurances")
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany("Insurances")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePlan");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.PlannedProcedure", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.ClaimProcedure", "ClaimProcedure")
                        .WithMany()
                        .HasForeignKey("ClaimProcedureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CloudDentalOffice.Portal.Models.TreatmentPlan", "TreatmentPlan")
                        .WithMany("PlannedProcedures")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaimProcedure");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.TreatmentPlan", b =>
                {
                    b.HasOne("CloudDentalOffice.Portal.Models.Patient", "Patient")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDentalOffice.Portal.Models.Provider", "Provider")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Claim", b =>
                {
                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.InsurancePlan", b =>
                {
                    b.Navigation("PatientInsurances");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Claims");

                    b.Navigation("Insurances");

                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.Provider", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Claims");

                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("CloudDentalOffice.Portal.Models.TreatmentPlan", b =>
                {
                    b.Navigation("PlannedProcedures");
                });
#pragma warning restore 612, 618
        }
    }
}
