CREATE TABLE `eformfielddef` (
  `EFormFieldDefNum` bigint(20) NOT NULL AUTO_INCREMENT,
  `EFormDefNum` bigint(20) NOT NULL,
  `FieldType` tinyint(4) NOT NULL,
  `DbLink` varchar(255) NOT NULL,
  `ValueLabel` text NOT NULL,
  `ItemOrder` int(11) NOT NULL,
  `PickListVis` varchar(255) NOT NULL,
  `PickListDb` varchar(255) NOT NULL,
  `IsHorizStacking` tinyint(4) NOT NULL,
  `IsTextWrap` tinyint(4) NOT NULL,
  `Width` int(11) NOT NULL,
  `FontScale` int(11) NOT NULL,
  `IsRequired` tinyint(4) NOT NULL,
  `ConditionalParent` varchar(255) NOT NULL,
  `ConditionalValue` varchar(255) NOT NULL,
  `LabelAlign` tinyint(4) NOT NULL,
  `SpaceBelow` int(11) NOT NULL,
  `ReportableName` varchar(255) NOT NULL,
  `IsLocked` tinyint(4) NOT NULL,
  `Border` tinyint(4) NOT NULL,
  `IsWidthPercentage` tinyint(4) NOT NULL,
  `MinWidth` int(11) NOT NULL,
  `WidthLabel` int(11) NOT NULL,
  `SpaceToRight` int(11) NOT NULL,
  PRIMARY KEY (`EFormFieldDefNum`),
  KEY `EFormDefNum` (`EFormDefNum`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
